# Generated by Django 5.1.4 on 2025-05-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Новый'), ('USED', 'Б/У')], max_length=6),
        ),
    ]
