# Generated by Django 5.1.4 on 2025-05-08 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], max_length=6),
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ad_receiver_requests_created', to='ads.ad')),
                ('ad_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_ad_sender_requests_created', to='ads.ad')),
            ],
        ),
    ]
