# Generated by Django 5.1.4 on 2025-05-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_condition_exchangeproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
